% Example Units Data
Units{1} = FixedPlatform('Project',app.UserData,...
    'Name','Miller Platform',...
    'Type',categorical("Conventional Jacket"),...
    'Mass',47316,...
    'Length',77.5,...
    'Width',43,...
    'Height',267.2,...
    'Accommodation',categorical("Yes"),...
    'CrewCapacity',45,...
    'CraneCapacity',500,...
    'FirstModule',categorical("Top"));
Units{2} = Topside('Project',app.UserData,...
    'Name','Miller Topside',...
    'Type',categorical("Topside"),...
    'Mass',28732,...
    'Length',77.5,...
    'Width',45,...
    'Height',144.65,...
    'Accommodation',categorical("Yes"),...
    'CrewCapacity',45,...
    'CraneCapacity',500,...
    'Parent',Units(1));
Units{3} = Module('Project',app.UserData,...
    'Name','Accommodation',...
    'Type',categorical("Accommodation Module"),...
    'Mass',2258,...
    'Length',24,...
    'Width',30,...
    'Height',24,...
    'Parent',Units(2));
Units{4} = Module('Project',app.UserData,...
    'Name','Power Generation',...
    'Type',categorical("Utility Module"),...
    'Mass',3949,...
    'Length',24,...
    'Width',45,...
    'Height',18.5,...
    'Parent',Units(2));
Units{5} = Module('Project',app.UserData,...
    'Name','Process (Separation)',...
    'Type',categorical("Process Module"),...
    'Mass',4246,...
    'Length',32,...
    'Width',20,...
    'Height',29.94,...
    'Parent',Units(2));
Units{6} = Module('Project',app.UserData,...
    'Name','Process (Gas Compression)',...
    'Type',categorical("Process Module"),...
    'Mass',4088,...
    'Length',32,...
    'Width',20,...
    'Height',29.59,...
    'Parent',Units(2));
Units{7} = Module('Project',app.UserData,...
    'Name','Drilling/ Wellbay',...
    'Type',categorical("Process Module"),...
    'Mass',4899,...
    'Length',21.5,...
    'Width',51,...
    'Height',20.15,...
    'Parent',Units(2));
Units{8} = Module('Project',app.UserData,...
    'Name','Drilling (Substructure & Skidbase)',...
    'Type',categorical("Process Module"),...
    'Mass',1336,...
    'Length',23,...
    'Width',26,...
    'Height',30,...
    'Parent',Units(2));
Units{9} = Module('Project',app.UserData,...
    'Name','Drilling Derrick',...
    'Type',categorical("Structural Module"),...
    'Mass',212,...
    'Length',20,...
    'Width',20,...
    'Height',46,...
    'Parent',Units(2));
Units{10} = Module('Project',app.UserData,...
    'Name','Cellar Deck',...
    'Type',categorical("Structural Module"),...
    'Mass',6674,...
    'Length',71,...
    'Width',30,...
    'Height',11.5,...    
    'Include',1,...
    'Parent',Units(2));
Units{11} = Module('Project',app.UserData,...
    'Name','Flare Tower',...
    'Type',categorical("Structural Module"),...
    'Mass',391,...
    'Length',12,...
    'Width',12,...
    'Height',113,...
    'Include',1,...
    'Parent',Units(2));
Units{12} = Module('Project',app.UserData,...
    'Name','Helideck',...
    'Type',categorical("Structural Module"),...
    'Mass',154,...
    'Length',31,...
    'Width',30,...
    'Height',4,...
    'Include',1,...
    'Parent',Units(2));
Units{13} = Module('Project',app.UserData,...
    'Name','Exhaust Tower',...
    'Type',categorical("Structural Module"),...
    'Mass',438,...
    'Length',24,...
    'Width',8.8,...
    'Height',37,...
    'Parent',Units(2));
Units{14} = Module('Project',app.UserData,...
    'Name','Wireline Logging Unit',...
    'Type',categorical("Utility Module"),...
    'Mass',87,...
    'Length',8.2,...
    'Width',8.2,...
    'Height',5,...
    'Parent',Units(2));

Units{15} = Substructure('Project',app.UserData,...
    'Name','Miller Substructure',...
    'Type',categorical("Substructure"),...
    'Mass',18584,...
    'Length',71,...
    'Width',55,...
    'Height',122.5,...
    'Parent',Units(1));

Units{16} = Module('Project',app.UserData,...
    'Name','Miller Jacket',...
    'Type',categorical("Fixed Steel Jacket"),...
    'Mass',18584,...
    'Length',71,...
    'Width',55,...
    'Height',122.5,...
    'Include',0,...
    'Color',[0.9 0.8 0.1],...
    'Parent',Units(15));

Units{1}.Children = Units([2 15]);
Units{2}.Children = Units(3:14);
Units{15}.Children = Units(16);
%%
Connections = Connection.empty;
Connections(end+1) = Connection('Project',app.UserData,...
    'Name','Connection 1',...
    'Type',categorical("Structural"),...
    'Source',Units{3},...
    'Target',Units{5},...
    'SFace',5,...
    'TFace',2,...
    'Offset',[0,5,-18.5]);
Connections(end+1) = Connection('Project',app.UserData,...
    'Name','Connection 2',...
    'Type',categorical("Structural"),...
    'Source',Units{3},...
    'Target',Units{6},...
    'SFace',5,...
    'TFace',2,...
    'Offset',[0,-15,-18.5]);

Connections(end+1) = Connection('Project',app.UserData,...
    'Name','Connection 3',...
    'Type',categorical("Structural"),...
    'Source',Units{4},...
    'Target',Units{5},...
    'SFace',5,...
    'TFace',2,...
    'Offset',[0,-2.5,0]);
Connections(end+1) = Connection('Project',app.UserData,...
    'Name','Connection 4',...
    'Type',categorical("Structural"),...
    'Source',Units{4},...
    'Target',Units{6},...
    'SFace',5,...
    'TFace',2,...
    'Offset',[0,-22.5,0]);

Connections(end+1) = Connection('Project',app.UserData,...
    'Name','Connection 5',...
    'Type',categorical("Structural"),...
    'Source',Units{5},...
    'Target',Units{6},...
    'SFace',1,...
    'TFace',4,...
    'Offset',[0,0,0]);
Connections(end+1) = Connection('Project',app.UserData,...
    'Name','Connection 6',...
    'Type',categorical("Structural"),...
    'Source',Units{5},...
    'Target',Units{7},...
    'SFace',5,...
    'TFace',2,...
    'Offset',[0,5.5,0]);

Connections(end+1) = Connection('Project',app.UserData,...
    'Name','Connection 7',...
    'Type',categorical("Structural"),...
    'Source',Units{6},...
    'Target',Units{7},...
    'SFace',5,...
    'TFace',2,...
    'Offset',[0,25,0]);

Connections(end+1) = Connection('Project',app.UserData,...
    'Name','Connection 8',...
    'Type',categorical("Root"),...
    'Source',Units{7},...
    'Target',Units{10},...
    'SFace',6,...
    'TFace',3,...
    'Offset',[6.5,-10.5,0]);

Connections(end+1) = Connection('Project',app.UserData,...
    'Name','Connection 9',...
    'Type',categorical("Root"),...
    'Source',Units{5},...
    'Target',Units{10},...
    'SFace',6,...
    'TFace',3,...
    'Offset',[-15,-5,0]);

Connections(end+1) = Connection('Project',app.UserData,...
    'Name','Connection 10',...
    'Type',categorical("Root"),...
    'Source',Units{6},...
    'Target',Units{10},...
    'SFace',6,...
    'TFace',3,...
    'Offset',[-15,15,0]);

Connections(end+1) = Connection('Project',app.UserData,...
    'Name','Connection 11',...
    'Type',categorical("Root"),...
    'Source',Units{4},...
    'Target',Units{10},...
    'SFace',6,...
    'TFace',3,...
    'Offset',[-47,-7.5,0]);

Connections(end+1) = Connection('Project',app.UserData,...
    'Name','Connection 12',...
    'Type',categorical("Root"),...
    'Source',Units{11},...
    'Target',Units{7},...
    'SFace',2,...
    'TFace',5,...
    'Offset',[0,51,-20.15]);

Connections(end+1) = Connection('Project',app.UserData,...
    'Name','Connection 13',...
    'Type',categorical("Root"),...
    'Source',Units{8},...
    'Target',Units{7},...
    'SFace',6,...
    'TFace',3,...
    'Offset',[1.5,0,0]);

Connections(end+1) = Connection('Project',app.UserData,...
    'Name','Connection 14',...
    'Type',categorical("Root"),...
    'Source',Units{3},...
    'Target',Units{4},...
    'SFace',6,...
    'TFace',3,...
    'Offset',[0,7.5,0]);

Connections(end+1) = Connection('Project',app.UserData,...
    'Name','Connection 15',...
    'Type',categorical("Root"),...
    'Source',Units{14},...
    'Target',Units{5},...
    'SFace',6,...
    'TFace',3,...
    'Offset',[-23.8,11.8,0]);

Connections(end+1) = Connection('Project',app.UserData,...
    'Name','Connection 16',...
    'Type',categorical("Root"),...
    'Source',Units{9},...
    'Target',Units{8},...
    'SFace',6,...
    'TFace',3,...
    'Offset',[-1.5,3,0]);

Connections(end+1) = Connection('Project',app.UserData,...
    'Name','Connection 17',...
    'Type',categorical("Root"),...
    'Source',Units{12},...
    'Target',Units{3},...
    'SFace',6,...
    'TFace',3,...
    'Offset',[-10,-15,0]);

Connections(end+1) = Connection('Project',app.UserData,...
    'Name','Connection 18',...
    'Type',categorical("Root"),...
    'Source',Units{13},...
    'Target',Units{4},...
    'SFace',6,...
    'TFace',3,...
    'Offset',[0,37.5,0]);

Connections(end+1) = Connection('Project',app.UserData,...
    'Name','Connection 19',...
    'Type',categorical("Root"),...
    'Source',Units{10},...
    'Target',Units{16},...
    'SFace',6,...
    'TFace',3,...
    'Offset',[0,15,0]);

%%

Vessels = Vessel.empty;

Vessels(end+1) = Vessel('Project',app.UserData,...
    'Name','Saipem 7000',...
    'Type',categorical("Heavy Lift"),...
    'IMONumber',int32(8501567),...
    'YearBuilt',1987,...
    'DeadweightTonnage',70000,...
    'DisplacementTonnage',172000,...
    'GrossTonnage',117812,...
    'NetTonnage',106030,...
    'LengthOverall',198,...
    'Beam',90.25,...
    'Depth',43.5,...
    'OperatingDepth',27.5,...
    'TransitDraft',10.5,...
    'TransitSpeed',9.5,...
    'CraneCapacity',14000,...
    'HoistRate',round(rand,1)+0.2,...
    'SlewRate',round(rand,1)+0.2,...
    'DeckLoad',15000,...
    'FreeDeckArea',6498,...
    'CrewCapacity',725,...
    'MinCrew',36,...
    'DynamicPositioningClass',categorical("DP3"),...
    'MinDowntime',7,...
    'MinVoyageDistance',50,...
    'MinRentalPeriod',14,...
    'TimeCharterRate',700000,...
    'VoyageCharterRate',25000,...
    'BareboatCharterRate',550000,...
    'MobilisationCost',3000000,...
    'DemobilisationCost',2000000,...
    'FuelConsumptionTransit',6000,... %litres per hour
    'FuelConsumptionDP',1500,...
    'FuelConsumptionMoored',1000,...
    'FuelType',categorical("Marine Fuel Oil"));

Vessels(end+1) = Vessel('Project',app.UserData,...
    'Name','North Sea Giant',...
    'Type',categorical("Multi-Purpose Support"),...
    'IMONumber',int32(9524073),...
    'YearBuilt',2011,...
    'DeadweightTonnage',12705,...
    'DisplacementTonnage',26000,...
    'GrossTonnage',18151,...
    'NetTonnage',16335,...
    'LengthOverall',153.6,...
    'Beam',30,...
    'Depth',9,...
    'OperatingDepth',5.4,...
    'TransitDraft',6.8,...
    'TransitSpeed',11.5,...
    'CraneCapacity',400,...
    'HoistRate',round(rand,1)+0.2,...
    'SlewRate',round(rand,1)+0.2,...
    'DeckLoad',8800,...
    'FreeDeckArea',1676,...
    'CrewCapacity',120,...
    'MinCrew',6,...
    'DynamicPositioningClass',categorical("DP4"),...
    'MinDowntime',1,...
    'MinVoyageDistance',30,...
    'MinRentalPeriod',2,...
    'TimeCharterRate',100000,...
    'VoyageCharterRate',15000,...
    'BareboatCharterRate',70000,...
    'MobilisationCost',350000,...
    'DemobilisationCost',300000,...
    'FuelConsumptionTransit',1500,... %litres per hour
    'FuelConsumptionDP',350,...
    'FuelConsumptionMoored',250,...
    'FuelType',categorical("Marine Fuel Oil"));


Vessels(end+1) = Vessel('Project',app.UserData,...
    'Name','Atlantic Guardian',...
    'Type',categorical("Cable Laying"),...
    'IMONumber',int32(9239355),...
    'YearBuilt',2001,...
    'DeadweightTonnage',3538,...
    'DisplacementTonnage',8000,...
    'GrossTonnage',7172,...
    'NetTonnage',2151,...
    'LengthOverall',103.49,...
    'Beam',18,...
    'Depth',7,...
    'OperatingDepth',4.2,...
    'TransitDraft',5.75,...
    'TransitSpeed',13.5,...
    'CraneCapacity',20,...
    'HoistRate',round(rand,1)+0.2,...
    'SlewRate',round(rand,1)+0.2,...
    'DeckLoad',2400,...
    'FreeDeckArea',677,...
    'CrewCapacity',45,...
    'MinCrew',7,...
    'DynamicPositioningClass',categorical("DP2"),...
    'MinDowntime',4,...
    'MinVoyageDistance',30,...
    'MinRentalPeriod',7,...
    'TimeCharterRate',110000,...
    'VoyageCharterRate',17000,...
    'BareboatCharterRate',80000,...
    'MobilisationCost',375000,...
    'DemobilisationCost',250000,...
    'FuelConsumptionTransit',1000,... %litres per hour
    'FuelConsumptionDP',120,...
    'FuelConsumptionMoored',75,...
    'FuelType',categorical("Marine Gas Oil"));


Vessels(end+1) = Vessel('Project',app.UserData,...
    'Name','North Sea Atlantic',...
    'Type',categorical("Multi-Purpose Support"),...
    'IMONumber',int32(9665073),...
    'YearBuilt',2014,...
    'DeadweightTonnage',9300,...
    'DisplacementTonnage',21000,...
    'GrossTonnage',15701,...
    'NetTonnage',12000,...
    'LengthOverall',144,...
    'Beam',27,...
    'Depth',8,...
    'OperatingDepth',4.8,...
    'TransitDraft',8.5,...
    'TransitSpeed',15,...
    'CraneCapacity',550,...
    'HoistRate',round(rand,1)+0.2,...
    'SlewRate',round(rand,1)+0.2,...
    'DeckLoad',7000,...
    'FreeDeckArea',1900,...
    'CrewCapacity',120,...
    'MinCrew',6,...
    'DynamicPositioningClass',categorical("DP3"),...
    'MinDowntime',2,...
    'MinVoyageDistance',30,...
    'MinRentalPeriod',2,...
    'TimeCharterRate',150000,...
    'VoyageCharterRate',16000,...
    'BareboatCharterRate',75000,...
    'MobilisationCost',275000,...
    'DemobilisationCost',250000,...
    'FuelConsumptionTransit',1250,... %litres per hour
    'FuelConsumptionDP',150,...
    'FuelConsumptionMoored',100,...
    'FuelType',categorical("Marine Gas Oil"));

Vessels(end+1) = Vessel('Project',app.UserData,...
    'Name','Maersk Forza',...
    'Type',categorical("Subsea Support"),...
    'IMONumber',int32(9392690),...
    'YearBuilt',2008,...
    'DeadweightTonnage',6578,...
    'DisplacementTonnage',8500,...
    'GrossTonnage',7694,...
    'NetTonnage',6500,...
    'LengthOverall',107.6,...
    'Beam',22,...
    'Depth',7,...
    'OperatingDepth',4.2,...
    'TransitDraft',7.15,...
    'TransitSpeed',11.1,...
    'CraneCapacity',250,...
    'HoistRate',round(rand,1)+0.2,...
    'SlewRate',round(rand,1)+0.2,...
    'DeckLoad',3200,...
    'FreeDeckArea',861,...
    'CrewCapacity',120,...
    'MinCrew',6,...
    'DynamicPositioningClass',categorical("DP2"),...
    'MinDowntime',2,...
    'MinVoyageDistance',50,...
    'MinRentalPeriod',2,...
    'TimeCharterRate',125000,...
    'VoyageCharterRate',12500,...
    'BareboatCharterRate',65000,...
    'MobilisationCost',315000,...
    'DemobilisationCost',300000,...
    'FuelConsumptionTransit',900,... %litres per hour
    'FuelConsumptionDP',100,...
    'FuelConsumptionMoored',55,...
    'FuelType',categorical("Marine Gas Oil"));

Vessels(end+1) = Vessel('Project',app.UserData,...
    'Name','Pioneering Spirit',...
    'Type',categorical("Heavy Lift"),...
    'IMONumber',int32(9593505),...
    'YearBuilt',2013,...
    'DeadweightTonnage',300000,...
    'DisplacementTonnage',932000,...
    'GrossTonnage',403342,...
    'NetTonnage',48000,...
    'LengthOverall',477,...
    'Beam',124,...
    'Depth',55,...
    'OperatingDepth',31,...
    'TransitDraft',18,...
    'TransitSpeed',14,...
    'CraneCapacity',48000,...
    'DeckLoad',48000,...
    'FreeDeckArea',21508,...
    'CrewCapacity',571,...
    'HoistRate',round(rand,1)+0.2,...
    'SlewRate',round(rand,1)+0.2,...
    'MinCrew',29,...
    'DynamicPositioningClass',categorical("DP3"),...
    'MinDowntime',7,...
    'MinVoyageDistance',75,...
    'MinRentalPeriod',30,...
    'TimeCharterRate',1200000,...
    'VoyageCharterRate',90000,...
    'BareboatCharterRate',900000,...
    'MobilisationCost',4000000,...
    'DemobilisationCost',3000000,...
    'FuelConsumptionTransit',9250,... %litres per hour
    'FuelConsumptionDP',3250,...
    'FuelConsumptionMoored',1500,...
    'FuelType',categorical("Diesel"));

Vessels(end+1) = Vessel('Project',app.UserData,...
    'Name','Seaway Strashnov',...
    'Type',categorical("Heavy Lift"),...
    'IMONumber',int32(9452701),...
    'YearBuilt',2011,...
    'DeadweightTonnage',48000,...
    'DisplacementTonnage',79000,...
    'GrossTonnage',47426,...
    'NetTonnage',48000,...
    'LengthOverall',183,...
    'Beam',47,...
    'Depth',13,...
    'OperatingDepth',10,...
    'TransitDraft',8.5,...
    'TransitSpeed',13,...
    'CraneCapacity',5000,...
    'DeckLoad',5000,...
    'FreeDeckArea',4300,...
    'CrewCapacity',220,...
    'HoistRate',round(rand,1)+0.2,...
    'SlewRate',round(rand,1)+0.2,...
    'MinCrew',10,...
    'DynamicPositioningClass',categorical("DP3"),...
    'MinDowntime',1,...
    'MinVoyageDistance',50,...
    'MinRentalPeriod',15,...
    'TimeCharterRate',100000,...
    'VoyageCharterRate',50000,...
    'BareboatCharterRate',50000,...
    'MobilisationCost',1000000,...
    'DemobilisationCost',500000,...
    'FuelConsumptionTransit',190,... %litres per hour
    'FuelConsumptionDP',87,...
    'FuelConsumptionMoored',39,...
    'FuelType',categorical("Marine Gas Oil"));

Vessels(end+1) = Vessel('Project',app.UserData,...
    'Name','SSCV Sleipnir',...
    'Type',categorical("Heavy Lift"),...
    'IMONumber',int32(9781425),...
    'YearBuilt',2019,...
    'DeadweightTonnage',155702,...
    'DisplacementTonnage',273700,...
    'GrossTonnage',232880,...
    'NetTonnage',70794,...
    'LengthOverall',220,...
    'Beam',102,...
    'Depth',49,...
    'OperatingDepth',23,...
    'TransitDraft',12,...
    'TransitSpeed',11,...
    'CraneCapacity',20000,...
    'DeckLoad',20000,...
    'FreeDeckArea',7650,...
    'CrewCapacity',400,...
    'HoistRate',round(rand,1)+0.2,...
    'SlewRate',round(rand,1)+0.2,...
    'MinCrew',120,...
    'DynamicPositioningClass',categorical("DP3"),...
    'MinDowntime',3,...
    'MinVoyageDistance',60,...
    'MinRentalPeriod',14,...
    'TimeCharterRate',275000,...
    'VoyageCharterRate',25000,...
    'BareboatCharterRate',275000,...
    'MobilisationCost',3000000,...
    'DemobilisationCost',2000000,...
    'FuelConsumptionTransit',11000,... %litres per hour
    'FuelConsumptionDP',5500,...
    'FuelConsumptionMoored',1200,...
    'FuelType',categorical("Marine Gas Oil"));

Vessels(end+1) = Vessel('Project',app.UserData,...
    'Name','Thialf',...
    'Type',categorical("Heavy Lift"),...
    'IMONumber',int32(8757740),...
    'YearBuilt',1985,...
    'DeadweightTonnage',129221,...
    'DisplacementTonnage',198750,...
    'GrossTonnage',136709,...
    'NetTonnage',41012,...
    'LengthOverall',202,...
    'Beam',88,...
    'Depth',50,...
    'OperatingDepth',32,...
    'TransitDraft',12,...
    'TransitSpeed',12,...
    'CraneCapacity',14200,...
    'DeckLoad',7300,...
    'FreeDeckArea',8800,...
    'CrewCapacity',736,...
    'HoistRate',round(rand,1)+0.2,...
    'SlewRate',round(rand,1)+0.2,...
    'MinCrew',36,...
    'DynamicPositioningClass',categorical("DP3"),...
    'MinDowntime',7,...
    'MinVoyageDistance',50,...
    'MinRentalPeriod',14,...
    'TimeCharterRate',500000,...
    'VoyageCharterRate',25000,...
    'BareboatCharterRate',1000000,...
    'MobilisationCost',4000000,...
    'DemobilisationCost',4000000,...
    'FuelConsumptionTransit',4500,... %litres per hour
    'FuelConsumptionDP',2000,...
    'FuelConsumptionMoored',1000,...
    'FuelType',categorical("Marine Gas Oil"));

%%
Ports = Port.empty;

Ports(end+1) = Port('Project',app.UserData,...
    'Name','Aberdeen Harbour',...
    'TotalQuayside',5900,...
    'MaxLOA',165,...
    'MaxBeam',30,...
    'MaxDraft',8.5,...
    'MinChannelWidth',70,...
    'MaxCraneCapacity',1000);

Ports(end+1) = Port('Project',app.UserData,...
    'Name','Able Seaton Yard',...
    'TotalQuayside',1500,...
    'MaxLOA',306,...
    'MaxBeam',40,...
    'MaxDraft',11,...
    'MinChannelWidth',142,...
    'MaxCraneCapacity',28000);

Ports(end+1) = Port('Project',app.UserData,...
    'Name','Port of Nigg',...
    'TotalQuayside',910,...
    'MaxLOA',241,...
    'MaxBeam',50,...
    'MaxDraft',11,...
    'MinChannelWidth',122,...
    'MaxCraneCapacity',40000);

Ports(end+1) = Port('Project',app.UserData,...
    'Name','Lerwick Port',...
    'TotalQuayside',4600,...
    'MaxLOA',400,...
    'MaxBeam',50,...
    'MaxDraft',40,...
    'MinChannelWidth',95,...
    'MaxCraneCapacity',11200);

Ports(end+1) = Port('Project',app.UserData,...
    'Name','Kvaerner Stord Yard',...
    'TotalQuayside',620,...
    'MaxLOA',266,...
    'MaxBeam',40,...
    'MaxDraft',15,...
    'MinChannelWidth',80,...
    'MaxCraneCapacity',1050);

Ports(end+1) = Port('Project',app.UserData,...
    'Name','Forth Ports Dundee',...
    'TotalQuayside',1304,...
    'MaxLOA',350,...
    'MaxBeam',50,...
    'MaxDraft',12.8,...
    'MinChannelWidth',300,...
    'MaxCraneCapacity',2100);

%%
Sites = Site.empty;

Sites(end+1) = Site('Project',app.UserData,... %Aberdeen Harbour
    'Name','Aberdeen Harbour Site',...
    'Type',categorical("Port"),...
    'Latitude',57.143,...
    'Longitude',-2.079);
Ports(1).Site = Sites(end);

Sites(end+1) = Site('Project',app.UserData,... %Able Seaton Yard
    'Name','Able Seaton Yard Site',...
    'Type',categorical("Port"),...
    'Latitude',54.634,...
    'Longitude',-1.192);
Ports(2).Site = Sites(end);

Sites(end+1) = Site('Project',app.UserData,... %Nigg Energy
    'Name','Port of Nigg Site',...
    'Type',categorical("Port"),...
    'Latitude',57.698,...
    'Longitude',-4.025);
Ports(3).Site = Sites(end);

Sites(end+1) = Site('Project',app.UserData,... %Lerwick Port
    'Name','Lerwick Port Site',...
    'Type',categorical("Port"),...
    'Latitude',60.155,...
    'Longitude',-1.143);
Ports(4).Site = Sites(end);

Sites(end+1) = Site('Project',app.UserData,... %Kvaerner Stord Yard
    'Name','Kvaerner Stord Yard Site',...
    'Type',categorical("Port"),...
    'Latitude',59.764,...
    'Longitude',5.496);
Ports(5).Site = Sites(end);
for i = 1:length(Units)
    if isa(Units{i},"Module")
        Units{i}.Destination = Sites(end);
    end
end
for i = 1:length(Vessels)
    Vessels(i).StartSite = Sites(end);
end

Sites(end+1) = Site('Project',app.UserData,... %Dundee Port
    'Name','Forth Ports Dundee Site',...
    'Type',categorical("Port"),...
    'Latitude',56.463,...
    'Longitude',-2.947);
Ports(6).Site = Sites(end);

Sites(end+1) = Site('Project',app.UserData,... %Miller Platform
    'Name','Miller Platform Site',...
    'Type',categorical("Platform"),...
    'Latitude',58.722,...
    'Longitude',1.402,...
    'WaterDepth',102.4);

for i = 1:length(Units)
    Units{i}.Site = Sites(end);
end

