function NewProject(~,~,app)

delete(app.Children)
uiGrid = uigridlayout(app,[20 10]);

uiTitle = uilabel(uiGrid,...
    'Text','Create New Project',...
    'FontSize',32,...
    'HorizontalAlignment','center');
uiTitle.Layout.Row = [1 2];
uiTitle.Layout.Column = [3 8];

uiProjectNameLabel = uilabel(uiGrid,...
    'Text','New Project Name:',...
    'FontSize',18,...
    'HorizontalAlignment','right');
uiProjectNameLabel.Layout.Row = 5;
uiProjectNameLabel.Layout.Column = [2 3];

uiProjectNameEdit = uieditfield(uiGrid,...
    'Value','NewProject1',...
    'FontSize',18,...
    'HorizontalAlignment','center');
uiProjectNameEdit.Layout.Column = [4 7];

uiSaveLocLabel = uilabel(uiGrid,...
    'Text','Save Location:',...
    'FontSize',18,...
    'HorizontalAlignment','right');
uiSaveLocLabel.Layout.Row = 7;
uiSaveLocLabel.Layout.Column = [2 3];

uiSaveLocEdit = uieditfield(uiGrid,...
    'Value',cd,...
    'FontSize',18,...
    'HorizontalAlignment','center');
uiSaveLocEdit.Layout.Column = [4 7];

uiSaveLocButton = uibutton(uiGrid,...
    'Text','Browse...',...
    'FontSize',20,...
    'HorizontalAlignment','center',...
    'ButtonPushedFcn',{@UpdateSaveLoc,app,uiSaveLocEdit});

uiBackButton = uibutton(uiGrid,...
    'Text','Back',...
    'FontSize',20,...
    'HorizontalAlignment','center',...
    'ButtonPushedFcn',{@StartMenu,app});
uiBackButton.Layout.Row = 18;
uiBackButton.Layout.Column = 3;

uiConfirmButton = uibutton(uiGrid,...
    'Text','Confirm',...
    'FontSize',20,...
    'HorizontalAlignment','center',...
    'ButtonPushedFcn',{@CreateProject,app,uiSaveLocEdit});
uiConfirmButton.Layout.Row = 18;
uiConfirmButton.Layout.Column = 8;
end