function StartMenu(~,~,app)

delete(app.Children)
uiGrid = uigridlayout(app,[10 10]);

uiTitle = uilabel(uiGrid,...
    'Text','Decommissioning Decision Support System',...
    'FontSize',56,...
    'HorizontalAlignment','center');
uiTitle.Layout.Row  = [1 4];
uiTitle.Layout.Column  = [1 10];

uiNewProject = uibutton(uiGrid,...
    'Text','New Project',...
    'FontSize',20,...
    'HorizontalAlignment','center',...
    'ButtonPushedFcn',{@NewProject,app});
uiNewProject.Layout.Row = [5];
uiNewProject.Layout.Column = [4 7];

uiLoadProject = uibutton(uiGrid,...
    'Text','Load Project',...
    'FontSize',20,...
    'HorizontalAlignment','center');
uiLoadProject.Layout.Row = [6];
uiLoadProject.Layout.Column = [4 7];

uiHelp = uibutton(uiGrid,...
    'Text','Help',...
    'FontSize',20,...
    'HorizontalAlignment','center');
uiHelp.Layout.Row = [7];
uiHelp.Layout.Column = [4 7];






end