function AddUnit(~,~,app)

uiAddUnitPanel = findobj(app,'UserData','uiAddUnitPanel');

uiAddUnitGrid = uigridlayout(uiAddUnitPanel,[10 10]);

uiAddUnitTypeLabel = uilabel(uiAddUnitGrid,...
    'Text','Select Unit Type:',...
    'FontSize',12,...
    'FontWeight','Bold');
uiAddUnitTypeLabel.Layout.Column = [1 2];

% uiAddUnitSubTypeLabel = uilabel(uiAddUnitGrid,...
%     'Text','Sub-Unit Types:',...
%     'FontSize',12,...
%     'FontWeight','Bold');
% uiAddUnitSubTypeLabel.Layout.Column = 3;
% 
% uiAddUnitAddedSubLabel = uilabel(uiAddUnitGrid,...
%     'Text','Added Sub-Units:',...
%     'FontSize',12,...
%     'FontWeight','Bold');
% uiAddUnitAddedSubLabel.Layout.Column = 5;

uiAddUnitPropetiesLabel = uilabel(uiAddUnitGrid,...
    'Text','Unit Properties:',...
    'FontSize',12,...
    'FontWeight','Bold');
uiAddUnitPropetiesLabel.Layout.Column = [3 5];

uiAddUnitTypeTree = uitree(uiAddUnitGrid,'UserData','uiAddUnitTypeTree',...
    'SelectionChangedFcn',{@AddUnitTypeTreeNodeChanged,app});
uiAddUnitTypeTree.Layout.Row = [2 9];
uiAddUnitTypeTree.Layout.Column = [1 2];

% uiAddUnitSubList = uilistbox(uiAddUnitGrid,...
%     'Items',{''},'Enable','off');
% uiAddUnitSubList.Layout.Row = [2 9];
% uiAddUnitSubList.Layout.Column = 3;
% 
% uiAddUnitAddSubButton = uibutton(uiAddUnitGrid,...
%     'Text','>',...
%     'FontSize',12,...
%     'HorizontalAlignment','center',...
%     'Enable','off',...
%     'ButtonPushedFcn',{@AddUnitAddSubUnit,app});
% uiAddUnitAddSubButton.Layout.Row = 5;
% uiAddUnitAddSubButton.Layout.Column = 4;
% 
% uiAddUnitDelSubButton = uibutton(uiAddUnitGrid,...
%     'Text','<',...
%     'FontSize',12,...
%     'HorizontalAlignment','center',...
%     'Enable','off',...
%     'ButtonPushedFcn',{@AddUnitAddSubUnit,app});
% uiAddUnitDelSubButton.Layout.Row = 6;
% uiAddUnitDelSubButton.Layout.Column = 4;
% 
% uiAddUnitAddedSubList = uilistbox(uiAddUnitGrid,...
%     'Items',{''},'Enable','off');
% uiAddUnitAddedSubList.Layout.Row = [2 9];
% uiAddUnitAddedSubList.Layout.Column = 5;

uiAddUnitPropetiesTable = uitable(uiAddUnitGrid,'Enable','off');
uiAddUnitPropetiesTable.Layout.Row = [2 9];
uiAddUnitPropetiesTable.Layout.Column = [3 5];

uiAddUnitConfirmButton = uibutton(uiAddUnitGrid,...
    'Text','Confirm',...
    'FontSize',12,...
    'HorizontalAlignment','center',...
    'ButtonPushedFcn',{@ConfirmAddUnit,app});
uiAddUnitConfirmButton.Layout.Column = 4;
uiAddUnitConfirmButton.Layout.Row = 10;

uiAddUnitCancelButton = uibutton(uiAddUnitGrid,...
    'Text','Cancel',...
    'FontSize',12,...
    'HorizontalAlignment','center',...
    'ButtonPushedFcn',{@CancelAddUnit,app});
uiAddUnitCancelButton.Layout.Column = 5;
uiAddUnitCancelButton.Layout.Row = 10;

uiAddUnitPanel.Visible = 'on';

T = readtable('UnitTypes.xlsx','ReadVariableNames',false);
T2 = T{2:end,:};
names = categories(categorical(T{1,:}));
for i = 1:length(names)
        UnitTypeTreeNode1(i) = uitreenode(uiAddUnitTypeTree,'Text',names{i});
        subunits = categories(categorical(T2(:,i)));
        UnitTypeTreeNode1(i).NodeData = subunits;
end

% T = readtable('UnitTypes.xlsx','ReadVariableNames',false);
% T2 = T{2:end,:};
% names = categories(categorical(T{1,:}));
% for i = 1:length(names)
%         UnitTypeTreeNode1(i) = uitreenode(uiAddUnitTypeTree,'Text',names{i});
%         nodes = categories(categorical(T2(:,i)));
%         for j = 1:length(nodes)
%             UnitTypeTreeNode2(j) = uitreenode(UnitTypeTreeNode1(i),'Text',nodes{j});
%         end
% end


end